name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2 instance public DNS or IP address
        username: ${{ secrets.EC2_USERNAME }}  # EC2 instance username
        key: ${{ secrets.EC2_PRIVATE_KEY }}  # Private SSH key for authentication
        port: ${{ secrets.EC2_PORT }}  # SSH port (usually 22)
        script: |
          cd .  # Replace with your app directory path
          git pull origin main
          cd task-2-strapi-github
          npm run develop
